version: '3.8'

services:
  # The Next.js application service
  app:
    build:
      context: .
      # Use the development stage in the Dockerfile
      target: base
    ports:
      - "3000:3000"
    environment:
      # MongoDB connection URI, using the service name 'db'
      - MONGO_URI=mongodb://db:27017/nextjs-db
    volumes:
      # Mount the current directory into the container to enable hot-reloading
      - .:/app
    command: npm run dev
    depends_on:
      - db

  # The MongoDB database service
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      # Use a named volume for persistent data
      - mongo-data:/data/db

volumes:
  # Named volume to persist MongoDB data
  mongo-data:
